### ISSUE TITLE
Shape mismatch Error

### ISSUE THREAD

**Issue by Zuriich** [lmb-freiburg/demon#18]
I'm currently testing the tool using the example.py with sculpture1 and 2. I'm running it with CPU and getting the following error statement:

```
2017-09-05 11:01:05.625707: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 11:01:05.625729: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 11:01:05.625739: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
In file included from /usr/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/include/numpy/ndarrayobject.h:17,
                 from /usr/include/numpy/arrayobject.h:4,
                 from /home/zurich/.pyxbld/temp.linux-x86_64-3.5/pyrex/depthmotionnet/vis_cython.c:485:
/usr/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
Traceback (most recent call last):
  File "example.py", line 112, in <module>
    translation=translation)
  File "../python/depthmotionnet/vis.py", line 280, in visualize_prediction
    pointcloud = compute_point_cloud_from_depthmap(depth, K, R1, t1, n, img)
  File "../python/depthmotionnet/vis.py", line 47, in compute_point_cloud_from_depthmap
    return _compute_point_cloud_from_depthmap(depth, K, R, t, normals, colors)
  File "vis_cython.pyx", line 171, in depthmotionnet.vis_cython.compute_point_cloud_from_depthmap
ValueError: shape mismatch: colors (3, 256, 6), depth (192, 256)
```

I'm using an Anaconda environment with:

 - Python 3.5.4
 - tensorflow 1.3.0
 - VTK 7.1.1
 - Cmake 3.9.1

The Depth map I get is correct, but when it gets to the point cloud the error statement appears.

Thank you in andvanced.
Best regards,
Zuria.

**Comment by benjaminum** [comment]
The visualization should work now with the latest commit https://github.com/lmb-freiburg/demon/commit/44514c20b24b20eb5fc53a7cc7f801b7bf46a01b .

Thanks for reporting.

**Comment by Zuriich** [comment]
¡It works! Thank your for your fast answer.
