### ISSUE TITLE
undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by hby001** [lmb-freiburg/demon#26]
Hi,

When I run `python3 example.py`, an errror message showed up:
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from depthmotionnet.networks_original import *
  File "../python/depthmotionnet/networks_original.py", line 18, in <module>
    from .blocks_original import *
  File "../python/depthmotionnet/blocks_original.py", line 19, in <module>
    from .helpers import *
  File "../python/depthmotionnet/helpers.py", line 19, in <module>
    import lmbspecialops as sops
  File "/home/bingyao/demon/lmbspecialops/python/lmbspecialops.py", line 30, in <module>
    lmbspecialopslib = tf.load_op_library(_lib_path)
  File "/home/bingyao/.local/share/virtualenvs/demon_venv/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/bingyao/.local/share/virtualenvs/demon_venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/bingyao/demon/lmbspecialops/build/lib/lmbspecialops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

Any ideas?
Thanks,
Bingyao

**Comment by JiamingSuen** [comment]
You may refer to this https://github.com/lmb-freiburg/lmbspecialops/issues/3 and try to recompile tensorflow with a proper version of ABI.

**Comment by benjaminum** [comment]
If you are using tensorflow 1.4 try updating demon and lmbspecialops to the latest commits.

**Comment by hby001** [comment]
@benjaminum tried the latest commits and get new errors:

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from depthmotionnet.networks_original import *
  File "../python/depthmotionnet/networks_original.py", line 18, in <module>
    from .blocks_original import *
  File "../python/depthmotionnet/blocks_original.py", line 19, in <module>
    from .helpers import *
  File "../python/depthmotionnet/helpers.py", line 19, in <module>
    import lmbspecialops as sops
  File "/home/bingyao/demon/lmbspecialops/python/lmbspecialops.py", line 30, in <module>
    lmbspecialopslib = tf.load_op_library(_lib_path)
  File "/home/bingyao/.local/share/virtualenvs/demon_venv/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/bingyao/.local/share/virtualenvs/demon_venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/bingyao/demon/lmbspecialops/build/lib/lmbspecialops.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceENS_11StringPieceEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by kevin0932** [comment]
@benjaminum @hby001 I also tried the latest commits and get the same errors.

Is it something related to the option setting ABI "-D_GLIBCXX_USE_CXX11_ABI=0"? Would you please share some information on how to use DeMoN with tensorflow v1.4 built from source? Thanks a lot!

**Comment by benjaminum** [comment]
Yes, this looks now like an ABI problem.
Please have a look at the Issue mentioned by @JiamingSuen 

Try to start with a clean build directory and use a recent cmake version (>=3.7.1). Also make sure that there is no conflict between multiple installed tensorflow versions.

**Comment by hby001** [comment]
**Updating cmake to 3.10.0-rc4** solved the problem for me (was cmake 3.5). In my case, I did not build TensorFlow from source.

Configurations:
Ubuntu 16.04.3 LTS
Python 3.6
TensorFlow 1.4
Cmake 3.10.0-rc4

Thank you guys.

**Comment by rnunziata** [comment]
I am having the same issue: I am not sure how this can be a ABI issue as I have  other projects that use tensorflow with and with cuda and cudnn and they work fine.

**Comment by kevin0932** [comment]
@rnunziata I got it compiled successfully when I change the GCC compilers. I use GCC5 (coming with Ubuntu 16.04) for tensorflow 1.4 with "-D_GLIBCXX_USE_CXX11_ABI=0" or just GCC4 for tensorflow, while GCC 4.9 is used to build lmb-freiburg/lmbspecialops.

My other configurations:
Ubuntu 16.04.3 LTS
Python 3.6
TensorFlow 1.4
CMake 3.9

Hope it helps.

**Comment by rnunziata** [comment]
can you supply more detail of files you modified and where you made the changes. Did you compile tensorflow form source?

**Comment by kevin0932** [comment]
@rnunziata FYI, I didn't modify any files. if you compile tensorflow from source with gcc 5 (or later) compilers, just add the option as shown in the official tutorial (https://www.tensorflow.org/install/install_sources):
$ bazel build --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package 

When compiling DeMoN lmbspecialops, I just use GCC 4.9 compiler. I tried to set the option but failed. So I installed a separate GCC 4.9 compiler and compile it with GCC 4.9.

**Comment by rnunziata** [comment]
thanks...that worked. 
I think I was setting the cxx opts in the wrong place I am using cmake

set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -D_GLIBCXX_USE_CXX11_ABI=0" )
