### ISSUE TITLE
Cannot load liblz4.so

### ISSUE THREAD

**Issue by jn-z** [lmb-freiburg/demon#31]
Hi,

When I run python3 create_dataset_and_use_readerop.py , an errror message showed up:
Traceback (most recent call last):
File "../python/depthmotionnet/dataset_tools/lz4.py", line 24, in <module>
    liblz4 = CDLL(_lib_path)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /media/deep/文档/ubuntubf/test/demon/build/lz4/src/lz4-build/liblz4.so: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../python/depthmotionnet/dataset_tools/lz4.py", line 28, in <module>
    liblz4 = CDLL('liblz4.so')
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: liblz4.so: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "create_dataset_and_use_readerop.py", line 12, in <module>
    from depthmotionnet.dataset_tools import *
  File "../python/depthmotionnet/dataset_tools/__init__.py", line 19, in <module>
    from .view_io import *
  File "../python/depthmotionnet/dataset_tools/view_io.py", line 21, in <module>
    from .lz4 import lz4_uncompress, lz4_compress_HC
  File "../python/depthmotionnet/dataset_tools/lz4.py", line 30, in <module>
    raise RuntimeError('Cannot load liblz4.so')
RuntimeError: Cannot load liblz4.so

Any ideas?
Thanks,
Zhang-jn

**Comment by benjaminum** [comment]
Hi,

can you try the devel branch?
There seems to be a bugfix missing in the master branch.

**Comment by jn-z** [comment]
Thank you, the problem is solved, but  When I run python3 evaluation.py , an errror message showed up:
Traceback (most recent call last):
  File "evaluation.py", line 325, in <module>
    main()
  File "evaluation.py", line 284, in main
    eval_result = evaluate(pr_file, gt_file, depthmask=False, eigen_crop_gt_and_pred=True)
  File "../python/depthmotionnet/evaluation/evaluate_to_xarray.py", line 274, in evaluate
    gt_f = h5py.File(gt_file,'r')
  File "/home/deep/.local/share/virtualenvs/demon_venv/lib/python3.5/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/deep/.local/share/virtualenvs/demon_venv/lib/python3.5/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
Do you have any other suggestions? Thanks

**Comment by jn-z** [comment]
The above problem has been solved. Thank you.
