### ISSUE TITLE
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

### ISSUE THREAD

**Issue by 3togo** [lmb-freiburg/demon#51]
any help?

examples$ python3 evaluation.py 
Using /home/jc/git/demon/lmbspecialops/build/lib/lmbspecialops.so
Using /data/jc/git/demon/build/multivih5datareaderop/multivih5datareaderop.so
dataset= mvs
dataset_dir= ../datasets
creating predictions for mvs
2018-09-06 21:40:36.949891: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using data_format "channels_last"
number of test samples = 66,  test_iter = 66
opening ../datasets/mvs_test.h5
computing errors for mvs
Traceback (most recent call last):
  File "evaluation.py", line 327, in <module>
    main()
  File "evaluation.py", line 286, in main
    eval_result = evaluate(pr_file, gt_file, depthmask=False, eigen_crop_gt_and_pred=True)
  File "../python/depthmotionnet/evaluation/evaluate_to_xarray.py", line 274, in evaluate
    gt_f = h5py.File(gt_file,'r')
  File "/home/jc/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/jc/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

**Comment by 3togo** [comment]
It seems to me that mvs_test.h5 was corrupted.
Removing mvs from datasets in evaluation.py will fix but the problem. But why?
 #datasets = ('mvs', 'scenes11', 'rgbd', 'sun3d', 'nyu2')
    datasets = ('scenes11', 'rgbd', 'sun3d', 'nyu2')

**Comment by 3togo** [comment]
mvs_ground_truth.h5 file is corrupted 
removing this file will fix the problem

**Comment by freedom9393** [comment]
The reason I know is:
`Your download process was not complete, so your file is corrupted`
So, you have to re-download/re-save the file
