### ISSUE TITLE
AttributeError: module 'lmbspecialops' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by RichardHansir** [lmb-freiburg/demon#59]
hi,when i run python example.py  ,it shows error like 

2018-11-04 14:42:21.588402: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-04 14:42:21.660199: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-04 14:42:21.660461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.34GiB
2018-11-04 14:42:21.660489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-11-04 14:42:21.732112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "example.py", line 75, in <module>
    bootstrap_net = BootstrapNet(session, data_format)
  File "../python/depthmotionnet/networks_original.py", line 45, in __init__
    netFlow1_result = flow_block_demon_original(self.placeholder_image_pair, data_format=data_format )
  File "../python/depthmotionnet/blocks_original.py", line 141, in flow_block_demon_original
    conv1 = convrelu2_caffe_padding(name='conv1', inputs=image_pair, num_outputs=32, kernel_size=9, stride=2, **conv_params)
  File "../python/depthmotionnet/helpers.py", line 145, in convrelu2_caffe_padding
    **kwargs,
  File "/home/richard/.local/lib/python3.5/site-packages/tensorflow/python/layers/convolutional.py", line 608, in conv2d
    return layer.apply(inputs)
  File "/home/richard/.local/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 671, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/richard/.local/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/richard/.local/lib/python3.5/site-packages/tensorflow/python/layers/convolutional.py", line 192, in call
    return self.activation(outputs)
  File "../python/depthmotionnet/helpers.py", line 67, in myLeakyRelu
    return sops.leaky_relu(x, leak=0.1)
AttributeError: module 'lmbspecialops' has no attribute 'leaky_relu'

what can i do to solve this problem?

**Comment by vivasvan1** [comment]
same issue here

**Comment by ClementPinard** [comment]
You can probably now use tensorflow's leakyrelu since it's supposed to be the same as in lmbspecialops
https://www.tensorflow.org/api_docs/python/tf/nn/leaky_relu
